-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.categories
(
    category_id smallint NOT NULL,
    category_name character varying(15) NOT NULL,
    description text,
    picture bytea,
    PRIMARY KEY (category_id)
);

CREATE TABLE public.customer_customer_demo
(
    customer_id bpchar NOT NULL,
    customer_type_id bpchar NOT NULL,
    PRIMARY KEY (customer_id, customer_type_id)
);

CREATE TABLE public.customer_demographics
(
    customer_type_id bpchar NOT NULL,
    customer_desc text,
    PRIMARY KEY (customer_type_id)
);

CREATE TABLE public.customers
(
    customer_id bpchar NOT NULL,
    company_name character varying(40) NOT NULL,
    contact_name character varying(30),
    contact_title character varying(30),
    address character varying(60),
    city character varying(15),
    region character varying(15),
    postal_code character varying(10),
    country character varying(15),
    phone character varying(24),
    fax character varying(24),
    PRIMARY KEY (customer_id)
);

CREATE TABLE public.employee_territories
(
    employee_id smallint NOT NULL,
    territory_id character varying(20) NOT NULL,
    PRIMARY KEY (employee_id, territory_id)
);

CREATE TABLE public.employees
(
    employee_id smallint NOT NULL,
    last_name character varying(20) NOT NULL,
    first_name character varying(10) NOT NULL,
    title character varying(30),
    title_of_courtesy character varying(25),
    birth_date date,
    hire_date date,
    address character varying(60),
    city character varying(15),
    region character varying(15),
    postal_code character varying(10),
    country character varying(15),
    home_phone character varying(24),
    extension character varying(4),
    photo bytea,
    notes text,
    reports_to smallint,
    photo_path character varying(255),
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.order_details
(
    order_id smallint NOT NULL,
    product_id smallint NOT NULL,
    unit_price real NOT NULL,
    quantity smallint NOT NULL,
    discount real NOT NULL,
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE public.orders
(
    order_id smallint NOT NULL,
    customer_id bpchar,
    employee_id smallint,
    order_date date,
    required_date date,
    shipped_date date,
    ship_via smallint,
    freight real,
    ship_name character varying(40),
    ship_address character varying(60),
    ship_city character varying(15),
    ship_region character varying(15),
    ship_postal_code character varying(10),
    ship_country character varying(15),
    PRIMARY KEY (order_id)
);

CREATE TABLE public.products
(
    product_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 78 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    product_name character varying(40) NOT NULL,
    supplier_id smallint,
    category_id smallint,
    quantity_per_unit character varying(20),
    unit_price real,
    units_in_stock smallint,
    units_on_order smallint,
    reorder_level smallint,
    discontinued integer,
    PRIMARY KEY (product_id)
);

CREATE TABLE public.region
(
    region_id smallint NOT NULL,
    region_description bpchar NOT NULL,
    PRIMARY KEY (region_id)
);

CREATE TABLE public.shippers
(
    shipper_id smallint NOT NULL,
    company_name character varying(40) NOT NULL,
    phone character varying(24),
    PRIMARY KEY (shipper_id)
);

CREATE TABLE public.suppliers
(
    supplier_id smallint NOT NULL,
    company_name character varying(40) NOT NULL,
    contact_name character varying(30),
    contact_title character varying(30),
    address character varying(60),
    city character varying(15),
    region character varying(15),
    postal_code character varying(10),
    country character varying(15),
    phone character varying(24),
    fax character varying(24),
    homepage text,
    PRIMARY KEY (supplier_id)
);

CREATE TABLE public.territories
(
    territory_id character varying(20) NOT NULL,
    territory_description bpchar NOT NULL,
    region_id smallint NOT NULL,
    PRIMARY KEY (territory_id)
);

CREATE TABLE public.us_states
(
    state_id smallint NOT NULL,
    state_name character varying(100),
    state_abbr character varying(2),
    state_region character varying(50),
    PRIMARY KEY (state_id)
);

ALTER TABLE public.customer_customer_demo
    ADD FOREIGN KEY (customer_type_id)
    REFERENCES public.customer_demographics (customer_type_id)
    NOT VALID;


ALTER TABLE public.customer_customer_demo
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id)
    NOT VALID;


ALTER TABLE public.employee_territories
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.employee_territories
    ADD FOREIGN KEY (territory_id)
    REFERENCES public.territories (territory_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (reports_to)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.order_details
    ADD FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id)
    NOT VALID;


ALTER TABLE public.order_details
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (ship_via)
    REFERENCES public.shippers (shipper_id)
    NOT VALID;


ALTER TABLE public.products
    ADD FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id)
    NOT VALID;


ALTER TABLE public.products
    ADD FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id)
    NOT VALID;


ALTER TABLE public.territories
    ADD FOREIGN KEY (region_id)
    REFERENCES public.region (region_id)
    NOT VALID;

END;